name: main
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  ffigen: ^12.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

assets
